how to find version

In [2]:
import pandas as pd
pd.__version__

'3.0.1'

In [3]:
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : e04b26f375035e5106cb913e47b6db612f4ebb11
python                : 3.14.3
python-bits           : 64
OS                    : Windows
OS-release            : 11
Version               : 10.0.26200
machine               : AMD64
processor             : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_United States.1252

pandas                : 3.0.1
numpy                 : 2.4.2
dateutil              : 2.9.0.post0
pip                   : 26.0.1
Cython                : None
sphinx                : None
IPython               : 9.8.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : 3.10.8
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.5
psycopg2              : None
pymysql               : None
pyarrow               : None
pyiceberg             : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pytz                  : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
qtpy                  : None
pyqt5                 : None

# make a dataframe

In [4]:
df=pd.DataFrame({'colum A':[1,2,3],'colum B':[4,5,6]})
df.head()

   colum A  colum B
0        1        4
1        2        5
2        3        6

In [5]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
pd.DataFrame(arr)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [6]:
pd.DataFrame(np.random.rand(4,8))

,0,1,2,3,4,5,6,7
0,0.282471,0.630119,0.454552,0.986149,0.813096,0.798701,0.546839,0.546362
1,0.715410,0.647757,0.942348,0.481631,0.260430,0.189611,0.876836,0.066406
2,0.104075,0.177771,0.631969,0.903227,0.170816,0.803387,0.915558,0.967121
3,0.496371,0.641131,0.305276,0.576161,0.592150,0.587468,0.960289,0.937394

In [7]:
pd.DataFrame(np.random.rand(5,8),columns=list("ABCDEFGH"))

,A,B,C,D,E,F,G,H
0,0.934089,0.970839,0.921092,0.021541,0.089067,0.534108,0.487934,0.570239
1,0.324630,0.584393,0.676547,0.752588,0.508953,0.895282,0.820947,0.664836
2,0.033135,0.885873,0.345023,0.894325,0.183396,0.127681,0.503228,0.898248
3,0.457027,0.896663,0.532334,0.186913,0.817467,0.837437,0.809588,0.072894
4,0.673067,0.446594,0.590995,0.884278,0.544685,0.603602,0.133540,0.262264

# how to rename a column

In [8]:
df=pd.DataFrame({'colum A':[1,2,3],'colum B':[4,5,6]})
df

   colum A  colum B
0        1        4
1        2        5
2        3        6

In [9]:
df.rename(columns={"A_colum":"colum_a","B_colum":"col_b"},inplace=True)
df

   colum A  colum B
0        1        4
1        2        5
2        3        6

In [10]:
df.columns=["Col_a","col_b"]
df

   Col_a  col_b
0      1      4
1      2      5
2      3      6

In [11]:
# to replace any character
df.columns=df.columns.str.replace('_',' ')
df

   Col a  col b
0      1      4
1      2      5
2      3      6

In [12]:
# adding prefix
df=df.add_prefix('col_a')
df

   col_aCol a  col_acol b
0           1           4
1           2           5
2           3           6

In [13]:
# adding psuffix
df=df.add_suffix('baba_a')
df

   col_aCol ababa_a  col_acol bbaba_a
0                 1                 4
1                 2                 5
2                 3                 6

In [14]:
df.columns=['col_a','col_b']
df

   col_a  col_b
0      1      4
1      2      5
2      3      6

# Using template data

In [15]:
import pandas as pd
import numpy as np
import seaborn as sns
khashti=sns.load_dataset('titanic')
khashti.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [16]:
# summary
khashti.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [17]:
khashti.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [18]:
# saving a template data set
df.to_csv("khashti.csv")

In [19]:
khashti.to_excel("khashti.xlsx")

# Using your own data

In [20]:
import pandas as pd
df=pd.read_csv("khashti.csv")

# Reverse Row order

In [21]:
import seaborn as sns
import pandas as pd
df=sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [22]:
df.loc[::-1].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True

In [23]:
df.loc[::-1].reset_index(drop=True).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True
1,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
2,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
3,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
4,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True

# reverse colum

In [24]:
df.loc[:,::-1].head()

,alone,alive,embark_town,deck,adult_male,who,class,embarked,fare,parch,sibsp,age,sex,pclass,survived
0,False,no,Southampton,NaN,True,man,Third,S,7.2500,0,1,22.0,male,3,0
1,False,yes,Cherbourg,C,False,woman,First,C,71.2833,0,1,38.0,female,1,1
2,True,yes,Southampton,NaN,False,woman,Third,S,7.9250,0,0,26.0,female,3,1
3,False,yes,Southampton,C,False,woman,First,S,53.1000,0,1,35.0,female,1,1
4,True,no,Southampton,NaN,True,man,Third,S,8.0500,0,0,35.0,male,3,0

# select a colum by a data type

In [25]:
df.dtypes

survived          int64
pclass            int64
sex                 str
age             float64
sibsp             int64
parch             int64
fare            float64
embarked            str
class          category
who                 str
adult_male         bool
deck           category
embark_town         str
alive               str
alone              bool
dtype: object

# only select those have numeric

In [26]:
df.select_dtypes(include=['number']).head()

   survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500

In [27]:
df.select_dtypes(include=['object']).head()

C:\Users\codanic\AppData\Local\Temp\ipykernel_18180\1349317115.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=['object']).head()

      sex embarked    who  embark_town alive
0    male        S    man  Southampton    no
1  female        C  woman    Cherbourg   yes
2  female        S  woman  Southampton   yes
3  female        S  woman  Southampton   yes
4    male        S    man  Southampton    no

In [28]:
# for multiple dtypes
df.select_dtypes(include=['object','category']).head()
df.select_dtypes(include=['object']).head()

C:\Users\codanic\AppData\Local\Temp\ipykernel_18180\2470531386.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=['object','category']).head()
C:\Users\codanic\AppData\Local\Temp\ipykernel_18180\2470531386.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=['object']).head()

      sex embarked    who  embark_town alive
0    male        S    man  Southampton    no
1  female        C  woman    Cherbourg   yes
2  female        S  woman  Southampton   yes
3  female        S  woman  Southampton   yes
4    male        S    man  Southampton    no

In [29]:
df.select_dtypes(exclude=['object']).head()

,survived,pclass,age,sibsp,parch,fare,class,adult_male,deck,alone
0,0,3,22.0,1,0,7.2500,Third,True,NaN,False
1,1,1,38.0,1,0,71.2833,First,False,C,False
2,1,3,26.0,0,0,7.9250,Third,False,NaN,True
3,1,1,35.0,1,0,53.1000,First,False,C,False
4,0,3,35.0,0,0,8.0500,Third,True,NaN,True

In [30]:
# convert strings to number
df=pd.DataFrame({'col_A':['1.4','2','3','4','5'],
                  'col_B':['5','6','7','8','9']})
df

  col_A col_B
0   1.4     5
1     2     6
2     3     7
3     4     8
4     5     9

In [31]:
df.dtypes

col_A    str
col_B    str
dtype: object

In [32]:
df.astype({'col_A':'float64','col_B':'Float64'}).dtypes

col_A    float64
col_B    Float64
dtype: object

In [33]:
# conversion to numeric type
pd.to_numeric(df['col_A'],errors='coerce')
pd.to_numeric(df['col_B'],errors='coerce')

0    5
1    6
2    7
3    8
4    9
Name: col_B, dtype: int64

# reduce dataframe size

In [34]:
df=sns.load_dataset('titanic')
df.shape

(891, 15)

In [35]:
# df.sample(frac=0.1).shape
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

# copy data from clip board

In [36]:
# data set dowload
import pandas as pd
import seaborn as sns
df=sns.load_dataset('titanic')
df.to_excel('khashti.xlsx')

In [37]:
# read clipboard in python
df=pd.read_clipboard()

split datframe into two subset

In [38]:
len(df)

0

In [39]:
from random import random
khashti_1=df.sample(frac=0.50,random_state=1)
khashti_1.shape

(0, 14)

In [40]:
khashti_2=df.drop(khashti_1.index)
khashti_2.shape

(0, 14)

In [41]:
khashti_1.head()

Empty DataFrame
Columns: [give, me, a, pdf, of, real, life, intermediate, level, strings, methods, question, in, python]
Index: []

In [42]:
khashti_2.head()

Empty DataFrame
Columns: [give, me, a, pdf, of, real, life, intermediate, level, strings, methods, question, in, python]
Index: []

In [43]:
len(khashti_2)+len(khashti_1)

0

In [44]:
df1=khashti_1.append(khashti_2)
df1.shape

AttributeError: 'DataFrame' object has no attribute 'append'

# filetering a dataset

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.sex.unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [ ]:
df[(df.sex=='female')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [ ]:
df.age.unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [ ]:
df.embark_town.unique()
df[(df.embark_town=='Southampton')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [ ]:
df[((df.embark_town=='Southampton') | (df.embark_town=='Queenstown'))
   
    &
            (df.sex=='female')


   ]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [ ]:
df[df.embark_town.isin(['Queenstown'])].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
28,1,3,female,NaN,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
32,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True

In [ ]:
df[df.age>30]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

# filetering by large categories

In [ ]:
df.age.value_counts().nlargest(3)

age
24.0    30
22.0    27
18.0    26
Name: count, dtype: int64

In [ ]:
df.embark_town.value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [ ]:
df.who.value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [ ]:
counts = df['embark_town'].value_counts()

df[df.embark_town.isin(counts.nlargest(1).index)].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True

# splitting a string into multiple colum

In [47]:
import pandas as pd
df= pd.DataFrame({'name':['muhammed ahmed raza','ali afzal','sajjad ali','abu bakkar'],
                  'location':['lahore','pakistan','washignton','karachi']})

In [50]:
df[['first name','last name']]=df.name.str.split(' ',expand=True)
df

ValueError: Columns must be same length as key

In [55]:
import pandas as pd
import seaborn as sns
df=sns.load_dataset('titanic')

# Aggregate by muliple groups/functions

In [57]:
df.groupby('who').count()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone
who,,,,,,,,,,,,,,
child,83,83,83,83,83,83,83,83,83,83,13,83,83,83
man,537,537,537,413,537,537,537,537,537,537,99,537,537,537
woman,271,271,271,218,271,271,271,269,271,271,91,269,271,271

In [59]:
df.groupby('sex')

In [60]:
len(df.groupby('pclass'))

3

In [61]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [62]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [71]:
df.describe().loc[['min','25%']]
# or
df.describe().loc['min':'max','survived':'age']

     survived  pclass     age
min       0.0     1.0   0.420
25%       0.0     2.0  20.125
50%       0.0     3.0  28.000
75%       1.0     3.0  38.000
max       1.0     3.0  80.000

In [ ]:
df

In [73]:
df.survived.mean()

np.float64(0.3838383838383838)

In [75]:
df.groupby(['sex','class']).survived.mean()

sex     class
female  First     0.968085
        Second    0.921053
        Third     0.500000
male    First     0.368852
        Second    0.157407
        Third     0.135447
Name: survived, dtype: float64

In [76]:
df.groupby(['sex','class']).survived.mean().unstack()

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

# continous to catagorical

In [ ]:
pd.cut(df.age,bins=[0,18,],labels=['child','young_adult'])