# how to import data set in python using pandas library
written by : jamal khan jamal\
Date: 06.01.2026\
email: jamalkhanmrd151@gmail.com

In [2]:
# step 1 
# importing libraries
import pandas as pd

In [3]:
# step 2
# reading dataset
df = pd.read_excel("pandas_01_day6.xlsx") # write the path if you want to load data from day 1 to day 6

In [5]:
df

    height  weight favourite_dish
0      5.8     101  Chicken Pulao
1      6.2      92        Biryani
2      5.9      62  Karahi Ghosht
3      5.9      95  Chicken Pulao
4      5.9      55  Chicken Pulao
..     ...     ...            ...
82     5.4      55          Pasta
83     5.9      75  Karahi Ghosht
84     5.4      61        Biryani
85     6.2      68  Chicken Pulao
86     5.1      96        Biryani

[87 rows x 3 columns]

In [4]:
# df.head()
df.head(10)

   height  weight favourite_dish
0     5.8     101  Chicken Pulao
1     6.2      92        Biryani
2     5.9      62  Karahi Ghosht
3     5.9      95  Chicken Pulao
4     5.9      55  Chicken Pulao
5     5.3      59        Biryani
6     5.6      50          Pasta
7     5.9      76        Biryani
8     5.1      78        Biryani
9     5.4      68        Biryani

In [7]:
df.tail()

    height  weight favourite_dish
82     5.4      55          Pasta
83     5.9      75  Karahi Ghosht
84     5.4      61        Biryani
85     6.2      68  Chicken Pulao
86     5.1      96        Biryani

In [9]:
df.shape

(87, 3)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   height          87 non-null     float64
 1   weight          87 non-null     int64
 2   favourite_dish  87 non-null     object
dtypes: float64(1), int64(1), object(1)
memory usage: 2.2+ KB